package schocken.marco.de.schocken.game.enums;

/**
 * Created by marco on 02.01.17.
 */

public enum Penalties {

    SCHOCKOUT,SCHOCKSIX,SCHOCKFIVE,SCHOCKFOUR,SCHOCKTHREE,SCHOCKTWO,GENERALSIX,GENERALFIVE,GENERALFOUR,GENERALTHREE,GENERALTWO,STREETSIX,STREETFIVE,STREETFOUR,STREETTHREE,STREETNUMBER;
}
